### PR TITLE
Make the email content UTF8 compatible

### PR DESCRIPTION
**Pull request by savvasha**

### CODE REVIEW

**Comment by centminmod** [comment]
Thanks for the contribution. FYI, sendmail isn't installed on all servers always as postfix MTA is installed by default on Centmin Mod if possible. Have you tested this yourself yet ?

**Comment by savvasha** [comment]
Yes, my locale command returns the same results as yours. 
With my code the email sent/received is like that:
`Legend: A = Active, M = Must Use, D = Drop-In, U = Update Available
Ενεργοποίηση λειτουργίας συντήρησης…
Λήψη αναβάθμισης από https://downloads.wordpress.org/plugin/ewww-image-optimizer.5.1.1.zip...
Αποσυμπίεση ενημέρωσης…
Εγκατάσταση τελευταίας έκδοσης…
Αφαίρεση προηγούμενης έκδοσης…
Το πρόσθετο ενημερώθηκε επιτυχώς.
Λήψη αναβάθμισης από https://downloads.wordpress.org/plugin/schema.zip...
Αποσυμπίεση ενημέρωσης…
Εγκατάσταση τελευταίας έκδοσης…
Αφαίρεση προηγούμενης έκδοσης…
Το πρόσθετο ενημερώθηκε επιτυχώς.
Απενεργοποίηση λειτουργίας συντήρησης…
name    old_version     new_version     status
ewww-image-optimizer    5.1.0   5.1.1   Updated
schema  1.7.6   1.7.7   Updated
Success: Updated 2 of 2 plugins.
Reloading nginx configuration (via systemctl):  [  OK  ]`

With original code is like that:
`Legend: A = Active, I = Inactive, M = Must Use, D = Drop-In, U = Update Available
M-NM-^[M-NM-.M-OM-^HM-NM-7 M-NM-1M-NM-=M-NM-1M-NM-2M-NM-,M-NM-8M-NM-<M-NM-9M-OM-^CM-NM-7M-OM-^B M-NM-1M-OM-^@M-OM-^L https://downloads.wordpress.org/plugin/olympus-google-fonts.1.9.8.zip...
M-NM-^QM-OM-^@M-NM-?M-OM-^CM-OM-^EM-NM-<M-OM-^@M-NM-/M-NM-5M-OM-^CM-NM-7 M-NM-5M-NM-=M-NM-7M-NM-<M-NM--M-OM-^AM-OM-^IM-OM-^CM-NM-7M-OM-^BM-bM-^@M-&
M-NM-^UM-NM-3M-NM-:M-NM-1M-OM-^DM-NM-,M-OM-^CM-OM-^DM-NM-1M-OM-^CM-NM-7 M-OM-^DM-NM-5M-NM-;M-NM-5M-OM-^EM-OM-^DM-NM-1M-NM-/M-NM-1M-OM-^B M-NM--M-NM-:M-NM-4M-NM-?M-OM-^CM-NM-7M-OM-^BM-bM-^@M-&
M-NM-^QM-OM-^FM-NM-1M-NM-/M-OM-^AM-NM-5M-OM-^CM-NM-7 M-OM-^@M-OM-^AM-NM-?M-NM-7M-NM-3M-NM-?M-OM-^MM-NM-<M-NM-5M-NM-=M-NM-7M-OM-^B M-NM--M-NM-:M-NM-4M-NM-?M-OM-^CM-NM-7M-OM-^BM-bM-^@M-&
M-NM-$M-NM-? M-OM-^@M-OM-^AM-OM-^LM-OM-^CM-NM-8M-NM-5M-OM-^DM-NM-? M-NM-5M-NM-=M-NM-7M-NM-<M-NM-5M-OM-^AM-OM-^NM-NM-8M-NM-7M-NM-:M-NM-5 M-NM-5M-OM-^@M-NM-9M-OM-^DM-OM-^EM-OM-^GM-OM-^NM-OM-^B.
name    old_version     new_version     status
olympus-google-fonts    1.9.0   1.9.8   Updated
Success: Updated 1 of 1 plugins.
Reloading nginx configuration (via systemctl):  [  OK  ]^M`

**Comment by centminmod** [comment]
I see you have have non-English system. Hard to test for that when I only use English so thanks for this note as it is far more than just wordpress emails I would have to make similar changes to all email routines in Centmin Mod. For now I made a separate test branch at https://github.com/centminmod/centminmod/commit/9c59cf3369584fc146b5e72bb27276dcb44a8c69 so you can see what corrections I did to your code.

1. $EMAIL and $EMAILFROM have to remove `()` brackets otherwise bash shell treats them as commands not variables
2. variables need to be escaped as they're enclosed in `<<END` `END` so $EMAIL becomes \$EMAIL so they're written into the script `/root/tools/wp_updater_${vhostname}.sh` as $EMAIL and not evaluated.
3. I added conditional check to ensure sendmail exists before sending otherwise fall back to previous method

Will have to test this some more first. And eventually will need to update all Centmin Mod's email sending routines where possible.

**Comment by savvasha** [comment]
Thanks for that!! What do you mean that I have a non-english system? My system locale variables are the following:
`locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
`

I just switched my Wordpress language to Greek.

The strange think is that if I run the scripts manually through ssh console, then all characters are appearing just fine.

Thanks anyway :)
Savvas

**Comment by centminmod** [comment]
Yeah that's what i mean Wordpress language.

> The strange think is that if I run the scripts manually through ssh console, then all characters are appearing just fine.

interesting if you add the following just below the DT= variable in your /root/tools/wp_updater_${vhostname}.sh script and then let it run via cronjob does it still come with gibberish ?

```
# set locale temporarily to english
# due to some non-english locale issues
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
```

**Comment by savvasha** [comment]
I made your proposed changes but the email still has the gibberish characters. I am suspecting the dos2unix , or I am wrong?

**Comment by centminmod** [comment]
there's a conditional in my changes so dos2unix old method would only happen if you didn't have sendmail binary 

if you have sendmail binary, then it will run your proposed sendmail method

but if you mean the exported language UTF8 not working, then guess need to use your method.

**Comment by savvasha** [comment]
Yes I was actually talking about using the dos2unix method instead of the sendmail method. For some reason dos2unix takes a readable text string and converts it to something unreadable. Is dos2unix needed after all?

**Comment by centminmod** [comment]
So when you remove just dos2unix part, your text sent is normal ?

**Pull request closed without merging**
